# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  # Add yaml dashboards
  # dashboards:
  #  lovelace-yaml:
  #    mode: yaml
  #    title: My Energy
  #    icon: mdi:home-lightning-bolt
  #    show_in_sidebar: true
  #    filename: lovelace-my-energy.yaml

python_script:

# MariaDB connection
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 30
  commit_interval: 20

influxdb:
  host: 192.168.178.17
  port: 8086
  database: homeassistant
  username: !secret influxdb_admin_user
  password: !secret influxdb_admin_pass
  max_retries: 3
  default_measurement: state

homeassistant:
  customize_glob: !include customize_glob.yaml
  customize: !include customize.yaml
  packages:
    calender: !include packages/calender-package.yaml
    dwd_pollenflug: !include packages/dwd-pollenflug-package.yaml
    dwd_weather_warnings: !include packages/dwd-weather-warnings-package.yaml
    geo_rss_feeds: !include packages/geo-rss-feeds-package.yaml
    heating: !include packages/heating-package.yaml
    hochwasser: !include packages/hochwasser-package.yaml
    huawei_solar_yield: !include packages/huawei-solar-yield-package.yaml
    huawei_solar_battery_card: !include packages/huawei-solar-battery-card-package.yaml
    huawei_solar_battery_correction: !include packages/huawei-solar-battery-correction-package.yaml
    huawei_solar_diagnostic: !include packages/huawei-solar-diagnostic-package.yaml
    huawei_solar_power_flow_card: !include packages/huawei-solar-power-flow-card-package.yaml
    huawei_solar_energy_flow_card: !include packages/huawei-solar-energy-flow-card-package.yaml
    illuminance: !include packages/illuminance-package.yaml
    mold_indicator: !include packages/mold-indicator-package.yaml
    moon_phase_image: !include packages/moon_phase_image-package.yaml
    mqtt_sensor: !include packages/mqtt-sensor-package.yaml
    pulsemeter: !include packages/pulsemeter-new-package.yaml
    shelly_light: !include packages/shelly-light-package.yaml
    shelly_sockets: !include packages/shelly-sockets-package.yaml
    # skyfield: !include packages/skyfield-package.yaml
    solcast_solar: !include packages/solcast-solar-package.yaml
    temperature_feels_like: !include packages/temperature-feels-like-package.yaml

shell_command:
  pushupdates_to_github: /bin/bash .gitpushupdates.sh

powercalc:

group:
  energy_counter:
    name: "Energy Counter Group"
    entities:
      - sensor.pulsemeter_54_power
      - group.room_101
  switchable_sockets:
    name: "041.1_Schaltbare-Steckdosen"
    entities:
      - switch.310_garten_teich_1_uv_lampe
      - switch.310_garten_teich_2_monitor_mc
      - switch.310_garten_teich_3_frei
      - switch.310_garten_teich_4_frei
      - switch.310_garten_teich_5_kugel
      - switch.310_garten_teich_6_stern
      - switch.310_garten_teich_7_wasserpumpe
      - switch.310_garten_teich_8_dosierer
  room_101:
    name: "Room_101"
    entities:
      - sensor.pulsemeter_38_power
      - light.101_buro_licht_schreibtisch
      - light.101_buro_licht_treppe

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.178.131
    token: 4f729fecd5e7b58849edf4dcb0099d8a
