blueprint:
  name: Restore Samba Backup sensor on startup
  description: Restore Samba Backup sensor on startup
  domain: automation
  input:
    addon:
      name: Samba Backup Addon
      description: Select samba backup addon.
      selector:
        addon: {}
  source_url: https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/blueprints/restore_samba_backup_sensor.yaml
mode: single
trigger:
- event: start
  platform: homeassistant
action:
- service: hassio.addon_stdin
  data:
    addon: !input addon
    input: restore-sensor
