# geo-rss-feeds
#

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: "past_day_all_earthquakes"
    radius: 1500

sensor:
  - platform: geo_rss_events
    name: European Emergency
    url: http://emergency.copernicus.eu/mapping/activations-rapid/feed
    radius: 500
    unit_of_measurement: "Incidents"
  - platform: geo_rss_events
    name: EMSC Earthquakes
    url: https://www.emsc-csem.org/service/rss/rss.php?typ=emsc
    radius: 1500
  - platform: emscrss
    name: EMCS Earthquakes
    radius: 1500
    magnitude: 4.0
